// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfQXCyvyMoN8zJVOb4BKgMdbTK7w2_OW4',
    appId: '1:144260798445:android:9c933d0eaf21fc1e7c79e4',
    messagingSenderId: '144260798445',
    projectId: 'authentication-afa13',
    storageBucket: 'authentication-afa13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN_oConeN1zLN-_FxLgIgRXhjLh16SFN0',
    appId: '1:144260798445:ios:068b628045af08837c79e4',
    messagingSenderId: '144260798445',
    projectId: 'authentication-afa13',
    storageBucket: 'authentication-afa13.appspot.com',
    androidClientId: '144260798445-20dqj5q6m7o92kgq89jnku63no3aa9dh.apps.googleusercontent.com',
    iosClientId: '144260798445-h0jht1bonj3aj78gu6079pqh68938ksc.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentication',
  );

}